# Generated by Django 5.2 on 2025-05-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Value',
            new_name='value',
        ),
    ]
